### ISSUE TITLE
Partial fit and mini batch kmeans support?

### ISSUE THREAD

**Issue by Dasyud** [Hzzone/torch_clustering#1]
Would it be possible to add support for a partial_fit method? I am fitting the clustering object during my neural net's training and want to incrementally fit it on batches of training data.

**Comment by Hzzone** [comment]
Refer to the answer of GPT with minimum changes.

```python
class PyTorchKMeans(BasicClustering):
    # ...

    def fit_predict_batches(self, X_batches: List[torch.Tensor]):
        # Perform clustering on the first batch of data
        labels = self.fit_predict(X_batches[0])
        
        # Perform clustering on subsequent batches of data, using the cluster centers from the previous iteration as initial centers
        for X in X_batches[1:]:
            labels = self.fit_predict(X, init_state=self.cluster_centers_)
        
        return labels

    def fit_predict(self, X: torch.Tensor, init_state=None):
        # ...
        for n_init in range(self.n_init):
            random_state = int(random_states[n_init])
            if init_state is None:
                old_state = self.initialize(X, random_state=random_state)
            else:
                old_state = init_state
            old_labels, inertia = self.predict(X, old_state)
            # ...

    # ...
```

Usage:

```python
clustering_model = PyTorchKMeans(metric='cosine',
                                 init='k-means++',
                                 random_state=0,
                                 n_clusters=1000,
                                 n_init=10,
                                 max_iter=300,
                                 tol=1e-4,
                                 distributed=False,
                                 verbose=True)

# Split the data into multiple batches
X_batches = [torch.randn(128000, 256).cuda() for _ in range(10)]

# Perform clustering on the data in batches
labels = clustering_model.fit_predict_batches(X_batches)
```

The main changes are:

1. Added a new method `fit_predict_batches` to perform clustering on data in batches. 
2. Inside the `fit_predict_batches` method, the first batch of data is clustered, and then subsequent batches are clustered using the cluster centers from the previous iteration as initial centers.
3. Modified the `fit_predict` method to accept an optional parameter `init_state` for specifying the initial cluster centers. If `init_state` is provided, it is directly used as the initial centers; otherwise, the initialization follows the original logic.

By calling the `fit_predict_batches` method, you can perform clustering on the data in batches, with each batch using the cluster centers from the previous iteration as initial centers. This approach can reduce memory usage and improve efficiency when dealing with large-scale data.

**Comment by Dasyud** [comment]
Thanks for the prompt response! I noticed that the initialize method already had an option to specify cluster centres, and that you were storing the cluster centres at the end of fit_predict, although not using it. I accessed it and passed it as the init centres for subsequent fit calls. I believe it works the same as your solution.
